[workspace]
members = ["packages/*", "contracts/*"]

[profile.release.package.collection-factory]
codegen-units = 1
incremental = false

[profile.release.package.sg-marketplace]
codegen-units = 1
incremental = false

[profile.release.package.sg721]
codegen-units = 1
incremental = false

[profile.release.package.whitelist]
codegen-units = 1
incremental = false

[profile.release.package.royalty-group]
codegen-units = 1
incremental = false

[profile.release.package.sg-utils]
codegen-units = 1
incremental = false

[profile.release.package.sg-std]
codegen-units = 1
incremental = false

[profile.release]
rpath = false
lto = true
overflow-checks = true
opt-level = 3
debug = false
debug-assertions = false
